//
//  CharactersListViewController.swift
//  VIPArchitectureSample
//
//  Created by marco.iniguez.ollero on 23/2/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import UIKit

protocol CharactersListDisplayLogic where Self: UIViewController {
  
  func displayViewModel(_ viewModel: CharactersListModel.ViewModel)
}

final class CharactersListViewController: BaseViewController {
  
  typealias CharactersListFactory = CharactersListInteractorFactorable & CharactersListRouterFactorable

  private let mainView: CharactersListView
  private var interactor: CharactersListInteractable!
  private var router: CharactersListRouting!
  override var isNavigationBarHidden: Bool { false }

  
  required init(factory: CharactersListFactory, mainView: CharactersListView, dataSource: CharactersListModel.DataSource) {
    self.mainView = mainView
    
    super.init(nibName: nil, bundle: nil)
    
    let interactorFactory = factory as! CharactersListInteractorFactorable.InteractableFactory
    interactor = factory.makeInteractor(factory: interactorFactory, viewController: self, dataSource: dataSource)
    router = factory.makeRouter(viewController: self)
  }
  
  override func viewDidLoad() {
    super.viewDidLoad()
    interactor.doRequest(.prepareCharactersList(page: 0))
  }
  
  override func loadView() {
    mainView.delegate = self
    view = mainView
  }

  @available(*, unavailable)
  required init?(coder: NSCoder) {
    fatalError("init(coder:) has not been implemented, You shouldn't initialize the ViewController using Storyboards")
  }
}

// MARK: - CharactersListDisplayLogic
extension CharactersListViewController: CharactersListDisplayLogic {

  func displayViewModel(_ viewModel: CharactersListModel.ViewModel) {
    DispatchQueue.main.async {
      switch viewModel {

      case let .prepareCharactersList(viewModelData):
        self.navigationItem.title = viewModelData.title
        self.navigationItem.backBarButtonItem = UIBarButtonItem(title: "", style: .plain, target: nil, action: nil)
        self.mainView.updateDataSource(with: viewModelData)
        
      case let .showError(model):
        self.router.routeTo(.showError(model:model))
        
      }
    }
  }
  
  func errorRetryRequest() {
    self.mainView.retryRequest()
  }
}


// MARK: - CharactersListViewDelegate
extension CharactersListViewController: CharactersListViewDelegate {
  
  func nextPage(page: Int) {
    interactor.doRequest(.prepareCharactersList(page: page))
  }
  
}


// MARK: - Private Zone
private extension CharactersListViewController {
  
}
