//
//  ArtistDetailModel.swift
//  VIPArchitectureSample
//
//  Created by marco.iniguez.ollero on 24/2/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//


import Foundation

enum ArtistDetailModel {
  
  enum Request {
    case prepareView
  }
  
  enum Response {
    case prepareView(info: AlbumsLastFM)
    case showError(model: ErrorModel)
  }
  
  enum ViewModel {
    case showError(model: ErrorModel)
    case prepareView(viewModelData: ViewDataSource)
  }
  
  enum Route {
    case showError(model: ErrorModel)
  }
  
  struct ViewDataSource {
    let title: String
    let items: [CellModel]
  }
  
  struct CellModel {
    let title: String?
    let rank: String?
    let imageURL: URL?
    let description: String?
  }
  struct DataSource {
    var artistId: String
  }

}
