//
//  ArtistsListFactorable.swift
//  VIPArchitectureSample
//
//  Created by marco.iniguez.ollero on 23/2/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import UIKit

extension AppInjector {
  
  struct ArtistsListInjector {}
}

extension AppInjector.ArtistsListInjector: ArtistsListFactorable {}

protocol ArtistsListFactorable: ArtistsListInteractorFactorable, ArtistsListPresenterFactorable, ArtistsListRouterFactorable, ArtistsListServicesFactorable { }

protocol ArtistsListInteractorFactorable {
  typealias InteractableFactory = ArtistsListPresenterFactorable & ArtistsListServicesFactorable
  
  func makeInteractor(factory: InteractableFactory, viewController: ArtistsListDisplayLogic?, dataSource: ArtistsListModel.DataSource) -> ArtistsListInteractable
}

protocol ArtistsListPresenterFactorable {
  func makePresenter(viewController: ArtistsListDisplayLogic?) -> ArtistsListPresentationLogic
}

protocol ArtistsListRouterFactorable {
  func makeRouter(viewController: UIViewController?) -> ArtistsListRouting
}

extension ArtistsListFactorable {
  
  func makeInteractor(factory: InteractableFactory, viewController: ArtistsListDisplayLogic?, dataSource: ArtistsListModel.DataSource) -> ArtistsListInteractable {
    ArtistsListInteractor(factory: factory, viewController: viewController, dataSource: dataSource)
  }
  
  func makePresenter(viewController: ArtistsListDisplayLogic?) -> ArtistsListPresentationLogic {
    ArtistsListPresenter(viewController: viewController)
  }
  
  func makeRouter(viewController: UIViewController?) -> ArtistsListRouting {
    ArtistsListRouter(viewController: viewController)
  }
}


// MARK: - Service Factorable
protocol ArtistsListServicesFactorable {
  
  func makeFetchCharactersUseCase() -> FetchArtistsListUseCaseContract
}

extension ArtistsListServicesFactorable {
  
    func makeFetchCharactersUseCase() -> FetchArtistsListUseCaseContract {
        FetchArtistsListUseCase()
  }
}
