//
//  ArtistsListModel.swift
//  VIPArchitectureSample
//
//  Created by marco.iniguez.ollero on 23/2/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//


import Foundation

enum ArtistsListModel {
  enum Request {
    case prepareArtistList(page: Int)
    case itemPressed(index: Int)
  }
  
  enum Response {
    case prepareArtistList(data: [ArtistsListItemEntity])
    case showError(model: ErrorModel)
    case showDetail(id: String)
  }
  
  enum ViewModel {
    case showError(model: ErrorModel)
    case prepareArtistList(viewModelData: ViewDataSource)
    case showDetail(id: String)
  }
  
  enum Route {
    case showArtistDetail(id: String)
    case showError(model: ErrorModel)
  }
  
  struct ViewDataSource {
    let title: String
    let items: [CellModel]
  }
  
  struct CellModel {
    let name: String
    let imageURL: URL?
  }

  
  struct DataSource {
    var artistList: [ArtistsListItemEntity] = []
  }
}
