//
//  InitialSelectionModel.swift
//  VIPArchitectureSample
//
//  Created by marco.iniguez.ollero on 23/2/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//


import Foundation

enum InitialSelectionModel {
  
  enum Request {
    case prepareOptions
    case lastFOptionPressed
    case rickMortyPressed
  }
  
  enum Response {
    case prepareOptions
  }
  
  enum ViewModel {
    case prepareOptions(viewModelData: ViewDataSource)
  }
  
  enum Route {
    case showLastFMFlow
    case showRickMortyFlow
  }
  
  struct ViewDataSource {
    let title: String
    let questionTitle: String
    let titleLastFMButton: String
    let titleRickMortyButton: String
  }
  
  struct DataSource {
    
  }
}
