//
//  CharacterDetailMarvelModel.swift
//  VIPArchitectureSample
//
//  Created by marco.iniguez.ollero on 6/7/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//


import Foundation

enum CharacterDetailMarvelModel {
  
  enum Request {
    case prepareCharactersDetail
  }
  
  enum Response {
    case prepareCharactersDetail(data: ResultList)
    case showError(model: ErrorModel)
  }
  
  enum ViewModel {
    case showError(model: ErrorModel)
    case prepareCharactersDetail(viewModelData: ViewDataSource)
  }
  
  enum Route {
    case showError(model: ErrorModel)
  }
  
  struct ViewDataSource {
    let title: String
    let imageName: String?
    let sections: [SectionModel]
  }
  struct SectionModel {
    let title: String
    let items: [CellModel]
  }
  struct CellModel {
    let title: String
  }
  struct DataSource {
    let characterId: Int
  }
}
