platform :ios, '13.0'
inhibit_all_warnings!

target 'VIPArchitectureSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VIPArchitectureSample
  pod 'Alamofire', '5.4.0'
  pod 'Kingfisher'
  pod 'R.swift'

  target 'VIPArchitectureSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VIPArchitectureSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end

end
