//
//  CharactersListRickMortyModel.swift
//  VIPArchitectureSample
//
//  Created by marco.iniguez.ollero on 23/2/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//


import Foundation

enum CharactersListRickMortyModel {
  
  enum Request {
    case prepareCharactersListRickMorty(page: Int, nameFilter: String? = nil)
  }
  
  enum Response {
    case prepareCharactersListRickMorty(data: [CharactersListRickMortyItemEntity])
    case showError(model: ErrorModel)
  }
  
  enum ViewModel {
    case showError(model: ErrorModel)
    case prepareCharactersListRickMorty(viewModelData: ViewDataSource)
  }
  
  enum Route {
    case showError(model: ErrorModel)
  }
  
  struct ViewDataSource {
    let title: String
    let items: [CellModel]
  }
  
  struct CellModel {
    let name: String
    let imageURL: URL?
    let status: String?
    let species: String?
  }

  
  struct DataSource {
    var characterList: [CharactersListRickMortyItemEntity] = []
    var nameFilter: String? = nil
    var numberPages = 1
  }
}
