//
//  CharactersListMarvelRouter.swift
//  VIPArchitectureSample
//
//  Created by marco.iniguez.ollero on 5/7/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import UIKit

protocol CharactersListMarvelRouting {
  
  func routeTo(_ route: CharactersListMarvelModel.Route)
}

final class CharactersListMarvelRouter {
  
  private weak var viewController: UIViewController?
  
  init(viewController: UIViewController?) {
    self.viewController = viewController
  }
}


// MARK: - CharactersListMarvelRouting
extension CharactersListMarvelRouter: CharactersListMarvelRouting {
  
  func routeTo(_ route: CharactersListMarvelModel.Route) {
    DispatchQueue.main.async {
      switch route {
        
      case let .showCharacterDetailMarvel(id):
        self.showCharacterDetailMarvel(id: id)
        
      case let .showError(model):
        self.showErrorAlert(viewModel: model)
      }
    }
  }
}


// MARK: - Private Zone
private extension CharactersListMarvelRouter {
  
  func showErrorAlert(viewModel: ErrorModel) {
    self.viewController?.showAlertWithCompletion(
      title: viewModel.title,
      message: viewModel.message,
      okTitle: viewModel.retryButtonTitle,
      cancelTitle: nil,
      completionBlock: { (done) in
        if done {
            if let vc = self.viewController as? CharactersListMarvelViewController {
              vc.errorRetryRequest()
            }
        }
      })
  }
  
  func showCharacterDetailMarvel(id: Int) {
    let viewController = CharacterDetailMarvelViewController(factory: AppInjector.CharacterDetailMarvelInjector(), mainView: CharacterDetailMarvelView(), dataSource: CharacterDetailMarvelModel.DataSource(characterId: id))
    self.viewController?.navigationController?.pushViewController(viewController, animated: true)
  }
}
