//
//  CharactersListMarvelInteractor.swift
//  VIPArchitectureSample
//
//  Created by marco.iniguez.ollero on 5/7/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import Foundation

typealias CharactersListMarvelInteractable = CharactersListMarvelBusinessLogic & CharactersListMarvelDataStore

protocol CharactersListMarvelBusinessLogic {
  
  func doRequest(_ request: CharactersListMarvelModel.Request)
}

protocol CharactersListMarvelDataStore {
  var dataSource: CharactersListMarvelModel.DataSource { get }
}

final class CharactersListMarvelInteractor: CharactersListMarvelDataStore {
  
  var dataSource: CharactersListMarvelModel.DataSource
  
  private var factory: CharactersListMarvelInteractorFactorable.InteractableFactory
  private var presenter: CharactersListMarvelPresentationLogic
  var fetchCharacterListMarvelUseCase: FetchCharacterListMarvelUseCaseContract

  init(factory: CharactersListMarvelInteractorFactorable.InteractableFactory, viewController: CharactersListMarvelDisplayLogic?, dataSource: CharactersListMarvelModel.DataSource) {
    self.factory = factory
    self.dataSource = dataSource
    self.presenter = factory.makePresenter(viewController: viewController)
    self.fetchCharacterListMarvelUseCase = factory.makeFetchCharactersUseCase()
  }
}


// MARK: - CharactersListMarvelBusinessLogic
extension CharactersListMarvelInteractor: CharactersListMarvelBusinessLogic {
  
  func doRequest(_ request: CharactersListMarvelModel.Request) {
    DispatchQueue.global(qos: .userInitiated).async {
      
      switch request {
        
      case let .prepareCharactersListMarvel(page):
        self.prepareCharactersListMarvel(page: page)
        
      case let .itemPressed(index):
        self.presenter.presentResponse(.showDetail(id: self.dataSource.characterList[index].id))
      }
    }
  }
}


// MARK: - Private Zone
private extension CharactersListMarvelInteractor {
  
  func prepareCharactersListMarvel(page: Int) {
    if page == 0 {
      LoaderView.toggleUniversalLoadingView(true)
    }
      Task { @MainActor in
          do {
            let model = try await fetchCharacterListMarvelUseCase.execute(FetchCharacterListMarvelUseCaseParameters(page: page))
            LoaderView.toggleUniversalLoadingView(false)
            self.dataSource.characterList.append(contentsOf: model.items)
            self.presenter.presentResponse(.prepareCharactersListMarvel(data: self.dataSource.characterList))
          } catch {
              LoaderView.toggleUniversalLoadingView(false)
              let errorModel = ErrorHelper.createGenericError()
              self.presenter.presentResponse(.showError(model: errorModel))
          }
      }
  }
}
