//
//  CharacterDetailMarvelRouter.swift
//  VIPArchitectureSample
//
//  Created by marco.iniguez.ollero on 6/7/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import UIKit

protocol CharacterDetailMarvelRouting {
  
  func routeTo(_ route: CharacterDetailMarvelModel.Route)
}

final class CharacterDetailMarvelRouter {
  
  private weak var viewController: UIViewController?
  
  init(viewController: UIViewController?) {
    self.viewController = viewController
  }
}


// MARK: - CharacterDetailMarvelRouting
extension CharacterDetailMarvelRouter: CharacterDetailMarvelRouting {
  
  func routeTo(_ route: CharacterDetailMarvelModel.Route) {
    DispatchQueue.main.async {
      switch route {
        
      case let .showError(model):
        self.showErrorAlert(viewModel: model)
        
      }
    }
  }
}


// MARK: - Private Zone
private extension CharacterDetailMarvelRouter {
  
  func showErrorAlert(viewModel: ErrorModel) {
    self.viewController?.showAlertWithCompletion(
      title: viewModel.title,
      message: viewModel.message,
      okTitle: viewModel.retryButtonTitle,
      cancelTitle: nil,
      completionBlock: { (done) in
        if done {
            if let vc = self.viewController as? CharacterDetailMarvelViewController {
              vc.errorRetryRequest()
            }
        }
      })
  }
}
